namespace VulkanNative;

[Flags]
public enum VkAccessFlags : uint
{
    VK_ACCESS_INDIRECT_COMMAND_READ_BIT = 1U << 0,
    VK_ACCESS_INDEX_READ_BIT = 1U << 1,
    VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT = 1U << 2,
    VK_ACCESS_UNIFORM_READ_BIT = 1U << 3,
    VK_ACCESS_INPUT_ATTACHMENT_READ_BIT = 1U << 4,
    VK_ACCESS_SHADER_READ_BIT = 1U << 5,
    VK_ACCESS_SHADER_WRITE_BIT = 1U << 6,
    VK_ACCESS_COLOR_ATTACHMENT_READ_BIT = 1U << 7,
    VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT = 1U << 8,
    VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT = 1U << 9,
    VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT = 1U << 10,
    VK_ACCESS_TRANSFER_READ_BIT = 1U << 11,
    VK_ACCESS_TRANSFER_WRITE_BIT = 1U << 12,
    VK_ACCESS_HOST_READ_BIT = 1U << 13,
    VK_ACCESS_HOST_WRITE_BIT = 1U << 14,
    VK_ACCESS_MEMORY_READ_BIT = 1U << 15,
    VK_ACCESS_MEMORY_WRITE_BIT = 1U << 16,
    VK_ACCESS_NONE = 0,
    VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT = 1U << 25,
    VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXT = 1U << 26,
    VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT = 1U << 27,
    VK_ACCESS_CONDITIONAL_RENDERING_READ_BIT_EXT = 1U << 20,
    VK_ACCESS_COLOR_ATTACHMENT_READ_NONCOHERENT_BIT_EXT = 1U << 19,
    VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR = 1U << 21,
    VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR = 1U << 22,
    VK_ACCESS_FRAGMENT_DENSITY_MAP_READ_BIT_EXT = 1U << 24,
    VK_ACCESS_FRAGMENT_SHADING_RATE_ATTACHMENT_READ_BIT_KHR = 1U << 23,
    VK_ACCESS_COMMAND_PREPROCESS_READ_BIT_NV = 1U << 17,
    VK_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV = 1U << 18
}