namespace VulkanNative;

[Flags]
public enum VkAccelerationStructureCreateFlagsKHR : uint
{
    VK_ACCELERATION_STRUCTURE_CREATE_DEVICE_ADDRESS_CAPTURE_REPLAY_BIT_KHR = 1U << 0,
    VK_ACCELERATION_STRUCTURE_CREATE_DESCRIPTOR_BUFFER_CAPTURE_REPLAY_BIT_EXT = 1U << 3,
    VK_ACCELERATION_STRUCTURE_CREATE_MOTION_BIT_NV = 1U << 2
}