namespace VulkanNative;

[Flags]
public enum VkBufferUsageFlags : uint
{
    VK_BUFFER_USAGE_TRANSFER_SRC_BIT = 1U << 0,
    VK_BUFFER_USAGE_TRANSFER_DST_BIT = 1U << 1,
    VK_BUFFER_USAGE_UNIFORM_TEXEL_BUFFER_BIT = 1U << 2,
    VK_BUFFER_USAGE_STORAGE_TEXEL_BUFFER_BIT = 1U << 3,
    VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT = 1U << 4,
    VK_BUFFER_USAGE_STORAGE_BUFFER_BIT = 1U << 5,
    VK_BUFFER_USAGE_INDEX_BUFFER_BIT = 1U << 6,
    VK_BUFFER_USAGE_VERTEX_BUFFER_BIT = 1U << 7,
    VK_BUFFER_USAGE_INDIRECT_BUFFER_BIT = 1U << 8,
    VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT = 1U << 17,
    VK_BUFFER_USAGE_VIDEO_DECODE_SRC_BIT_KHR = 1U << 13,
    VK_BUFFER_USAGE_VIDEO_DECODE_DST_BIT_KHR = 1U << 14,
    VK_BUFFER_USAGE_TRANSFORM_FEEDBACK_BUFFER_BIT_EXT = 1U << 11,
    VK_BUFFER_USAGE_TRANSFORM_FEEDBACK_COUNTER_BUFFER_BIT_EXT = 1U << 12,
    VK_BUFFER_USAGE_CONDITIONAL_RENDERING_BIT_EXT = 1U << 9,
    VK_BUFFER_USAGE_ACCELERATION_STRUCTURE_BUILD_INPUT_READ_ONLY_BIT_KHR = 1U << 19,
    VK_BUFFER_USAGE_ACCELERATION_STRUCTURE_STORAGE_BIT_KHR = 1U << 20,
    VK_BUFFER_USAGE_SHADER_BINDING_TABLE_BIT_KHR = 1U << 10,
    VK_BUFFER_USAGE_SAMPLER_DESCRIPTOR_BUFFER_BIT_EXT = 1U << 21,
    VK_BUFFER_USAGE_RESOURCE_DESCRIPTOR_BUFFER_BIT_EXT = 1U << 22,
    VK_BUFFER_USAGE_PUSH_DESCRIPTORS_DESCRIPTOR_BUFFER_BIT_EXT = 1U << 26,
    VK_BUFFER_USAGE_MICROMAP_BUILD_INPUT_READ_ONLY_BIT_EXT = 1U << 23,
    VK_BUFFER_USAGE_MICROMAP_STORAGE_BIT_EXT = 1U << 24
}