namespace VulkanNative;

[Flags]
public enum VkFormatFeatureFlags : uint
{
    VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT = 1U << 0,
    VK_FORMAT_FEATURE_STORAGE_IMAGE_BIT = 1U << 1,
    VK_FORMAT_FEATURE_STORAGE_IMAGE_ATOMIC_BIT = 1U << 2,
    VK_FORMAT_FEATURE_UNIFORM_TEXEL_BUFFER_BIT = 1U << 3,
    VK_FORMAT_FEATURE_STORAGE_TEXEL_BUFFER_BIT = 1U << 4,
    VK_FORMAT_FEATURE_STORAGE_TEXEL_BUFFER_ATOMIC_BIT = 1U << 5,
    VK_FORMAT_FEATURE_VERTEX_BUFFER_BIT = 1U << 6,
    VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BIT = 1U << 7,
    VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT = 1U << 8,
    VK_FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT = 1U << 9,
    VK_FORMAT_FEATURE_BLIT_SRC_BIT = 1U << 10,
    VK_FORMAT_FEATURE_BLIT_DST_BIT = 1U << 11,
    VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT = 1U << 12
}