namespace VulkanNative;

[Flags]
public enum VkImageCreateFlags : uint
{
    VK_IMAGE_CREATE_SPARSE_BINDING_BIT = 1U << 0,
    VK_IMAGE_CREATE_SPARSE_RESIDENCY_BIT = 1U << 1,
    VK_IMAGE_CREATE_SPARSE_ALIASED_BIT = 1U << 2,
    VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT = 1U << 3,
    VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT = 1U << 4
}