namespace VulkanNative;

[Flags]
public enum VkImageCompressionFixedRateFlagsEXT : uint
{
    VK_IMAGE_COMPRESSION_FIXED_RATE_NONE_EXT = 0,
    VK_IMAGE_COMPRESSION_FIXED_RATE_1BPC_BIT_EXT = 1U << 0,
    VK_IMAGE_COMPRESSION_FIXED_RATE_2BPC_BIT_EXT = 1U << 1,
    VK_IMAGE_COMPRESSION_FIXED_RATE_3BPC_BIT_EXT = 1U << 2,
    VK_IMAGE_COMPRESSION_FIXED_RATE_4BPC_BIT_EXT = 1U << 3,
    VK_IMAGE_COMPRESSION_FIXED_RATE_5BPC_BIT_EXT = 1U << 4,
    VK_IMAGE_COMPRESSION_FIXED_RATE_6BPC_BIT_EXT = 1U << 5,
    VK_IMAGE_COMPRESSION_FIXED_RATE_7BPC_BIT_EXT = 1U << 6,
    VK_IMAGE_COMPRESSION_FIXED_RATE_8BPC_BIT_EXT = 1U << 7,
    VK_IMAGE_COMPRESSION_FIXED_RATE_9BPC_BIT_EXT = 1U << 8,
    VK_IMAGE_COMPRESSION_FIXED_RATE_10BPC_BIT_EXT = 1U << 9,
    VK_IMAGE_COMPRESSION_FIXED_RATE_11BPC_BIT_EXT = 1U << 10,
    VK_IMAGE_COMPRESSION_FIXED_RATE_12BPC_BIT_EXT = 1U << 11,
    VK_IMAGE_COMPRESSION_FIXED_RATE_13BPC_BIT_EXT = 1U << 12,
    VK_IMAGE_COMPRESSION_FIXED_RATE_14BPC_BIT_EXT = 1U << 13,
    VK_IMAGE_COMPRESSION_FIXED_RATE_15BPC_BIT_EXT = 1U << 14,
    VK_IMAGE_COMPRESSION_FIXED_RATE_16BPC_BIT_EXT = 1U << 15,
    VK_IMAGE_COMPRESSION_FIXED_RATE_17BPC_BIT_EXT = 1U << 16,
    VK_IMAGE_COMPRESSION_FIXED_RATE_18BPC_BIT_EXT = 1U << 17,
    VK_IMAGE_COMPRESSION_FIXED_RATE_19BPC_BIT_EXT = 1U << 18,
    VK_IMAGE_COMPRESSION_FIXED_RATE_20BPC_BIT_EXT = 1U << 19,
    VK_IMAGE_COMPRESSION_FIXED_RATE_21BPC_BIT_EXT = 1U << 20,
    VK_IMAGE_COMPRESSION_FIXED_RATE_22BPC_BIT_EXT = 1U << 21,
    VK_IMAGE_COMPRESSION_FIXED_RATE_23BPC_BIT_EXT = 1U << 22,
    VK_IMAGE_COMPRESSION_FIXED_RATE_24BPC_BIT_EXT = 1U << 23
}