namespace VulkanNative;

[Flags]
public enum VkImageCreateFlags : uint
{
    VK_IMAGE_CREATE_SPARSE_BINDING_BIT = 1U << 0,
    VK_IMAGE_CREATE_SPARSE_RESIDENCY_BIT = 1U << 1,
    VK_IMAGE_CREATE_SPARSE_ALIASED_BIT = 1U << 2,
    VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT = 1U << 3,
    VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT = 1U << 4,
    VK_IMAGE_CREATE_ALIAS_BIT = 1U << 10,
    VK_IMAGE_CREATE_SPLIT_INSTANCE_BIND_REGIONS_BIT = 1U << 6,
    VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT = 1U << 5,
    VK_IMAGE_CREATE_BLOCK_TEXEL_VIEW_COMPATIBLE_BIT = 1U << 7,
    VK_IMAGE_CREATE_EXTENDED_USAGE_BIT = 1U << 8,
    VK_IMAGE_CREATE_PROTECTED_BIT = 1U << 11,
    VK_IMAGE_CREATE_DISJOINT_BIT = 1U << 9
}