namespace VulkanNative;

[Flags]
public enum VkMemoryPropertyFlags : uint
{
    VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT = 1U << 0,
    VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT = 1U << 1,
    VK_MEMORY_PROPERTY_HOST_COHERENT_BIT = 1U << 2,
    VK_MEMORY_PROPERTY_HOST_CACHED_BIT = 1U << 3,
    VK_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT = 1U << 4,
    VK_MEMORY_PROPERTY_PROTECTED_BIT = 1U << 5,
    VK_MEMORY_PROPERTY_DEVICE_COHERENT_BIT_AMD = 1U << 6,
    VK_MEMORY_PROPERTY_DEVICE_UNCACHED_BIT_AMD = 1U << 7,
    VK_MEMORY_PROPERTY_RDMA_CAPABLE_BIT_NV = 1U << 8
}