namespace VulkanNative;

[Flags]
public enum VkPipelineStageFlagBits : uint
{
    VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT = 0,
    VK_PIPELINE_STAGE_DRAW_INDIRECT_BIT = 1,
    VK_PIPELINE_STAGE_VERTEX_INPUT_BIT = 2,
    VK_PIPELINE_STAGE_VERTEX_SHADER_BIT = 3,
    VK_PIPELINE_STAGE_TESSELLATION_CONTROL_SHADER_BIT = 4,
    VK_PIPELINE_STAGE_TESSELLATION_EVALUATION_SHADER_BIT = 5,
    VK_PIPELINE_STAGE_GEOMETRY_SHADER_BIT = 6,
    VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT = 7,
    VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT = 8,
    VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT = 9,
    VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT = 10,
    VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT = 11,
    VK_PIPELINE_STAGE_TRANSFER_BIT = 12,
    VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT = 13,
    VK_PIPELINE_STAGE_HOST_BIT = 14,
    VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT = 15,
    VK_PIPELINE_STAGE_ALL_COMMANDS_BIT = 16
}