namespace VulkanNative;

[Flags]
public enum VkPipelineStageFlags2 : ulong
{
    VK_PIPELINE_STAGE_2_NONE = 0,
    VK_PIPELINE_STAGE_2_TOP_OF_PIPE_BIT = 1UL << 0,
    VK_PIPELINE_STAGE_2_DRAW_INDIRECT_BIT = 1UL << 1,
    VK_PIPELINE_STAGE_2_VERTEX_INPUT_BIT = 1UL << 2,
    VK_PIPELINE_STAGE_2_VERTEX_SHADER_BIT = 1UL << 3,
    VK_PIPELINE_STAGE_2_TESSELLATION_CONTROL_SHADER_BIT = 1UL << 4,
    VK_PIPELINE_STAGE_2_TESSELLATION_EVALUATION_SHADER_BIT = 1UL << 5,
    VK_PIPELINE_STAGE_2_GEOMETRY_SHADER_BIT = 1UL << 6,
    VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT = 1UL << 7,
    VK_PIPELINE_STAGE_2_EARLY_FRAGMENT_TESTS_BIT = 1UL << 8,
    VK_PIPELINE_STAGE_2_LATE_FRAGMENT_TESTS_BIT = 1UL << 9,
    VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT = 1UL << 10,
    VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT = 1UL << 11,
    VK_PIPELINE_STAGE_2_ALL_TRANSFER_BIT = 1UL << 12,
    VK_PIPELINE_STAGE_2_BOTTOM_OF_PIPE_BIT = 1UL << 13,
    VK_PIPELINE_STAGE_2_HOST_BIT = 1UL << 14,
    VK_PIPELINE_STAGE_2_ALL_GRAPHICS_BIT = 1UL << 15,
    VK_PIPELINE_STAGE_2_ALL_COMMANDS_BIT = 1UL << 16,
    VK_PIPELINE_STAGE_2_COPY_BIT = 1UL << 32,
    VK_PIPELINE_STAGE_2_RESOLVE_BIT = 1UL << 33,
    VK_PIPELINE_STAGE_2_BLIT_BIT = 1UL << 34,
    VK_PIPELINE_STAGE_2_CLEAR_BIT = 1UL << 35,
    VK_PIPELINE_STAGE_2_INDEX_INPUT_BIT = 1UL << 36,
    VK_PIPELINE_STAGE_2_VERTEX_ATTRIBUTE_INPUT_BIT = 1UL << 37,
    VK_PIPELINE_STAGE_2_PRE_RASTERIZATION_SHADERS_BIT = 1UL << 38
}