namespace VulkanNative;

[Flags]
public enum VkPipelineCreateFlags : uint
{
    VK_PIPELINE_CREATE_DISABLE_OPTIMIZATION_BIT = 1U << 0,
    VK_PIPELINE_CREATE_ALLOW_DERIVATIVES_BIT = 1U << 1,
    VK_PIPELINE_CREATE_DERIVATIVE_BIT = 1U << 2,
    VK_PIPELINE_CREATE_VIEW_INDEX_FROM_DEVICE_INDEX_BIT = 1U << 3,
    VK_PIPELINE_CREATE_DISPATCH_BASE_BIT = 1U << 4,
    VK_PIPELINE_CREATE_FAIL_ON_PIPELINE_COMPILE_REQUIRED_BIT = 1U << 8,
    VK_PIPELINE_CREATE_EARLY_RETURN_ON_FAILURE_BIT = 1U << 9
}