namespace VulkanNative;

[Flags]
public enum VkShaderStageFlags : uint
{
    VK_SHADER_STAGE_VERTEX_BIT = 1U << 0,
    VK_SHADER_STAGE_TESSELLATION_CONTROL_BIT = 1U << 1,
    VK_SHADER_STAGE_TESSELLATION_EVALUATION_BIT = 1U << 2,
    VK_SHADER_STAGE_GEOMETRY_BIT = 1U << 3,
    VK_SHADER_STAGE_FRAGMENT_BIT = 1U << 4,
    VK_SHADER_STAGE_COMPUTE_BIT = 1U << 5,
    VK_SHADER_STAGE_ALL_GRAPHICS = 0x0000001F,
    VK_SHADER_STAGE_ALL = 0x7FFFFFFF,
    VK_SHADER_STAGE_RAYGEN_BIT_KHR = 1U << 8,
    VK_SHADER_STAGE_ANY_HIT_BIT_KHR = 1U << 9,
    VK_SHADER_STAGE_CLOSEST_HIT_BIT_KHR = 1U << 10,
    VK_SHADER_STAGE_MISS_BIT_KHR = 1U << 11,
    VK_SHADER_STAGE_INTERSECTION_BIT_KHR = 1U << 12,
    VK_SHADER_STAGE_CALLABLE_BIT_KHR = 1U << 13,
    VK_SHADER_STAGE_TASK_BIT_EXT = 1U << 6,
    VK_SHADER_STAGE_MESH_BIT_EXT = 1U << 7,
    VK_SHADER_STAGE_SUBPASS_SHADING_BIT_HUAWEI = 1U << 14,
    VK_SHADER_STAGE_CLUSTER_CULLING_BIT_HUAWEI = 1U << 19
}