namespace VulkanNative;

[Flags]
public enum VkShaderStageFlags : uint
{
    VK_SHADER_STAGE_VERTEX_BIT = 1U << 0,
    VK_SHADER_STAGE_TESSELLATION_CONTROL_BIT = 1U << 1,
    VK_SHADER_STAGE_TESSELLATION_EVALUATION_BIT = 1U << 2,
    VK_SHADER_STAGE_GEOMETRY_BIT = 1U << 3,
    VK_SHADER_STAGE_FRAGMENT_BIT = 1U << 4,
    VK_SHADER_STAGE_COMPUTE_BIT = 1U << 5,
    VK_SHADER_STAGE_ALL_GRAPHICS = 0x0000001F,
    VK_SHADER_STAGE_ALL = 0x7FFFFFFF
}