namespace VulkanNative;

[Flags]
public enum VkShaderStageFlagBits : uint
{
    VK_SHADER_STAGE_VERTEX_BIT = 0,
    VK_SHADER_STAGE_TESSELLATION_CONTROL_BIT = 1,
    VK_SHADER_STAGE_TESSELLATION_EVALUATION_BIT = 2,
    VK_SHADER_STAGE_GEOMETRY_BIT = 3,
    VK_SHADER_STAGE_FRAGMENT_BIT = 4,
    VK_SHADER_STAGE_COMPUTE_BIT = 5,
    VK_SHADER_STAGE_ALL_GRAPHICS = 0x0000001F,
    VK_SHADER_STAGE_ALL = 0x7FFFFFFF
}