namespace VulkanNative;

[Flags]
public enum VkShaderCreateFlagsEXT : uint
{
    VK_SHADER_CREATE_LINK_STAGE_BIT_EXT = 1U << 0,
    VK_SHADER_CREATE_ALLOW_VARYING_SUBGROUP_SIZE_BIT_EXT = 1U << 1,
    VK_SHADER_CREATE_REQUIRE_FULL_SUBGROUPS_BIT_EXT = 1U << 2,
    VK_SHADER_CREATE_NO_TASK_SHADER_BIT_EXT = 1U << 3,
    VK_SHADER_CREATE_DISPATCH_BASE_BIT_EXT = 1U << 4,
    VK_SHADER_CREATE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_EXT = 1U << 5,
    VK_SHADER_CREATE_FRAGMENT_DENSITY_MAP_ATTACHMENT_BIT_EXT = 1U << 6
}