namespace VulkanNative;

[Flags]
public enum VkSurfaceTransformFlagsKHR : uint
{
    VK_SURFACE_TRANSFORM_IDENTITY_BIT_KHR = 1U << 0,
    VK_SURFACE_TRANSFORM_ROTATE_90_BIT_KHR = 1U << 1,
    VK_SURFACE_TRANSFORM_ROTATE_180_BIT_KHR = 1U << 2,
    VK_SURFACE_TRANSFORM_ROTATE_270_BIT_KHR = 1U << 3,
    VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_BIT_KHR = 1U << 4,
    VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_90_BIT_KHR = 1U << 5,
    VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_180_BIT_KHR = 1U << 6,
    VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_270_BIT_KHR = 1U << 7,
    VK_SURFACE_TRANSFORM_INHERIT_BIT_KHR = 1U << 8
}