namespace VulkanNative;

[Flags]
public enum VkSwapchainCreateFlagsKHR : uint
{
    VK_SWAPCHAIN_CREATE_SPLIT_INSTANCE_BIND_REGIONS_BIT_KHR = 1U << 0,
    VK_SWAPCHAIN_CREATE_PROTECTED_BIT_KHR = 1U << 1,
    VK_SWAPCHAIN_CREATE_MUTABLE_FORMAT_BIT_KHR = 1U << 2,
    VK_SWAPCHAIN_CREATE_DEFERRED_MEMORY_ALLOCATION_BIT_EXT = 1U << 3
}